import NavBar from '@/components/NavBar.jsx'
import Product from '@/components/Product.jsx'
import './globals.css'
import { Inter } from 'next/font/google'
/*import mongodbConnect from '@/lib/mongodb' */

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
    /*await mongodbConnect()*/
    return (
        <html lang = "en">
            <body className={inter.className}>
                <NavBar />
                <Product />
                {children}
            </body>
        </html>
    )
}
